services:
  db:
    image: postgres:16-alpine
    container_name: im_db
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_DB: ${DB_NAME:-inventory-management}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-10tDbDQhic}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: im_backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    volumes:
      - static_volume:/app/static_root
      - media_volume:/app/media_root
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: im_frontend
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  app_network:
    driver: bridge
