# Generated by Django 6.0.4 on 2026-04-20 21:09

from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_admin_user(apps, schema_editor):
    User = apps.get_model("users", "User")
    if not User.objects.filter(email="admin@admin.com").exists():
        User.objects.create(
            email="admin@admin.com",
            password=make_password("admin321"),
            first_name="admin",
            last_name="",
            is_admin=True,
            is_staff=True,
        )


def remove_admin_user(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(email="admin@admin.com").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_admin'),
    ]

    operations = [
        migrations.RunPython(create_admin_user, remove_admin_user),
    ]
