# Generated by Django 6.0.4 on 2026-04-21 02:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('sku', models.CharField(max_length=100)),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('L', 'L'), ('mL', 'mL'), ('unit', 'unit')], max_length=10)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='organizations.organization')),
            ],
            options={
                'unique_together': {('org', 'sku')},
            },
        ),
    ]
